### ISSUE TITLE
Please add group support

### ISSUE THREAD

**Issue by natcl** [urbiworx/node-red-contrib-hue#1]
Hello,

As mentioned on the Node-Red group, it would be nice to have group support.

I think having it in the same object would simplify things.  Would there be a way to have a separator in the dropdown menu to separate groups and lights ?

Thanks !

**Comment by urbiworx** [comment]
Should work now.

**Comment by natcl** [comment]
Nice thanks !

## 

lecaude.com 
studioimaginaire.com
